---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-app-dkj-com-v1-myapp
  failurePolicy: Fail
  name: mmyapp.kb.io
  rules:
  - apiGroups:
    - app.dkj.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - myapps
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-app-dkj-com-v1-myapp
  failurePolicy: Fail
  name: vmyapp.kb.io
  rules:
  - apiGroups:
    - app.dkj.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - myapps
  sideEffects: None
