# permissions for end users to edit myapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-demo
    app.kubernetes.io/managed-by: kustomize
  name: myapp-editor-role
rules:
- apiGroups:
  - app.dkj.com
  resources:
  - myapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.dkj.com
  resources:
  - myapps/status
  verbs:
  - get
